### ISSUE TITLE
Can  you release your training data?

### ISSUE THREAD

**Issue by michelleqyhqyh** [lisasiyu/Cross-Align#2]

**Comment by lisasiyu** [comment]
Sure!
Here is the dataset, you can download directly.
De-En, Fr-En, Ro-En dataset：https://github.com/lilt/alignment-scripts/tree/master/preprocess 
Ja-En dataset：http://www.phontron.com/kftt/ 
Zh-En dataset：LDC corpus (not free, as far as i know)

**Comment by michelleqyhqyh** [comment]
Thank you very much!



---- Replied Message ----
| From | Siyu ***@***.***> |
| Date | 03/28/2023 12:22 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [lisasiyu/Cross-Align] Can you release your training data? (Issue #2) |

Sure!
Here is the dataset, you can download directly.
De-En, Fr-En, Ro-En dataset：https://github.com/lilt/alignment-scripts/tree/master/preprocess
Ja-En dataset：http://www.phontron.com/kftt/
Zh-En dataset：LDC corpus (not free, as far as i know)
